aws_region       = "us-east-1"
vpc_cidr         = "10.0.0.0/16"
allowed_ssh_cidr = "YOUR_IP/32"
db_username      = "velaaadmin"
db_password      = "REPLACE_WITH_STRONG_PASSWORD"
s3_bucket_name   = "vela-assets-YOUR_UNIQUE_SUFFIX"
